name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Bootstrap
        run: cdk bootstrap --require-approval never

      - name: Deploy
        run: npm run deploy:force
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
